on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: JDK Setup
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Maven build
        run: |
          mvn -B test
          
    super-lint:
      name: Sonar
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Run sonar analysis
          uses: sonarsource/sonarcloud-github-action@master
          
