on:
  push

jobs:
  build:
    name: Hello World
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: JDK Setup
        with:
          java-version: '11'
          cache: maven
      - name: Maven build
        run: |
          mvn clean install